{{- $kind := ternary "Role" "ClusterRole" .Values.namespaced -}}
{{- $kindSuffix := ternary "role" "cluster-role" .Values.namespaced -}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jsc.serviceAccountName" . }}
  {{- include "jsc.metadataNamespace" . | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $kind }}
metadata:
  name: {{ template "jsc.serviceAccountName" . }}-{{ $kindSuffix }}
  {{- include "jsc.metadataNamespace" . | nindent 2 }}
{{ tpl .Values.rbacRules . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ printf "%sBinding" $kind}}
metadata:
  name: {{ template "jsc.serviceAccountName" . }}-{{ $kindSuffix }}-binding
  {{- include "jsc.metadataNamespace" . | nindent 2 }}
subjects:
- kind: ServiceAccount
  name: {{ template "jsc.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ $kind }}
  name: {{ template "jsc.serviceAccountName" . }}-{{ $kindSuffix }}
  apiGroup: rbac.authorization.k8s.io